version: "3"
services:
        topwastedhoursbyvoreport:
                image: "shreyb/gracc-reporting:topwastedhoursbyvo-report_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/home/ifmon/log
                        - ${CONFIGDIR}:/home/ifmon/gracc-config
                        - /etc/localtime:/etc/localtime
                command: ["-s", "${YESTERDAY}", "-e", "${TODAY}", "-E", "${vo}", "-F", "GPGrid", "-c", "/home/ifmon/gracc-config/fife.toml", "-L", "/home/ifmon/log/topwastedhoursbyvo.log", "-d", "-n", "-v"]

