version: "3"
services:
        osgprobereport:
                image: "shreyb/gracc-reporting:osgprobe-report_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/gracc-config
                        - /etc/localtime:/etc/localtime
                command: ["-c", "/tmp/gracc-config/osg.toml", "-L", "/tmp/log/osgprobereport.log", "-d"]
