# OSG base image for gracc-reporting
FROM shreyb/gracc-reporting:osg_0.11.4b

# Executable
# ENTRYPOINT ["sh", "-c", "osgtopoppusagereport -s \"$starttime\" -e \"$endtime\" -N \"$number\" -d"]
ENTRYPOINT ["osgtopoppusagereport"]
