version: "3"
services:
        minervareport:
                image: "shreyb/gracc-reporting:minerva-report_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/home/ifmon/log
                        - ${CONFIGDIR}:/home/ifmon/gracc-config
                        - /etc/localtime:/etc/localtime
                command: ["-c", "/home/ifmon/gracc-config/minerva.toml", "-a"]   
