# General

default_logdir = '/var/log'
configured_vos = ['cdf', 'cdms', 'darkside', 'dune', 'gm2', 'mars', 'minerva', 'minos', 'mu2e', 'nova', 'sbnd', 'seaquest', 'uboone']

[elasticsearch]
    hostname = 'https://gracc.opensciencegrid.org/q'

# Email
# Set the global email related values under this section

[email]
    # This is the FQDN of the mail server, which GRACC will use to send the email
    smtphost = 'smtp.fnal.gov'

    [email.from]
        name = 'GRACC Operations'  # This is the real name from which the report appears to be emailed from
        email = 'sbhat@fnal.gov'  # This is the email from which the reports appears to be emailed from

    # Tester emails
    [email.test]
        names = ['Shreyas Bhat', 'Tanya Levshina']
        emails = ['sbhat@fnal.gov', 'tlevshin@fnal.gov']

# Report-specific parameters
# Note that in TOML, True and False must be all lowercase.  Seems weird, but there you go.

[efficiency]
  index_pattern='gracc.osg.raw-%Y.%m'

	[efficiency.cdf]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['willis@fnal.gov']

	[efficiency.cdms]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov']

	[efficiency.darkside]
		min_hours = 500
		min_efficiency = 0.35
		to_emails = ['kherner@fnal.gov']

	[efficiency.dune]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'trj@fnal.gov', 'afarbin@uta.edu', 'schellma@fnal.gov']

	[efficiency.gm2]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'lyon@fnal.gov']

	[efficiency.mars]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov']

	[efficiency.minerva]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'perdue@fnal.gov', 'druterbo@pas.rochester.edu']

	[efficiency.minos]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'wingmc@gmail.com']

	[efficiency.mu2e]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'kutschke@fnal.gov']
		commonname = '/CN=production/mu2egpvm01.fnal.gov'

	[efficiency.nova]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'ahimmel@fnal.gov']
		commonname = '/CN=novaproduction/nova-offline.fnal.gov'

	[efficiency.sbnd]
		min_hours = 500
		min_efficiency = 0.65
		to_emails = ['sbhat@fnal.gov', 'tlevshin@fnal.gov', 'petrillo@fnal.gov']

	[efficiency.seaquest]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'chenyc@fnal.gov', 'timm@fnal.gov']

	[efficiency.uboone]
		min_hours = 1000
		min_efficiency = 0.5
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'greenlee@fnal.gov', 'kirby@fnal.gov']
		commonname = '/CN=uboonepro/uboonegpvm01.fnal.gov'



[jobsuccessrate]
  index_pattern='gracc.osg.raw-%Y.%m'

	[jobsuccessrate.darkside]
		noproduction = true
		voname = '/fermilab/darkside/Role=*'
		to_emails = ['kherner@fnal.gov']

	[jobsuccessrate.dune]
		voname = '/dune/Role=Production/Capability=NULL'
		to_emails = ['trj@fnal.gov', 'tjyang@fnal.gov', 'opos@fnal.gov', 'dune-production@fnal.gov', 'schellma@fnal.gov']

	[jobsuccessrate.gm2]
		voname = '/fermilab/gm2/Role=Production/Capability=NULL'
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'gm2-production@listserv.fnal.gov']

	[jobsuccessrate.mu2e]
		voname = '/fermilab/mu2e/Role=Production/Capability=NULL'
		to_emails = ['gandr@fnal.gov', 'rlc@fnal.gov', 'kutschke@fnal.gov', 'fife-group@fnal.gov', 'opos@fnal.gov']

	[jobsuccessrate.nova]
		voname = '/fermilab/nova/Role=Production/Capability=NULL'
		# num_clusters = 100
		jobs_per_cluster = 20
		# num_failed_sites = 20
		# num_hosts_per_site = 20
		# errors_per_host = 20
		to_emails = ['dingpf@fnal.gov', 'fife-group@fnal.gov', 'opos@fnal.gov', 'o9h8i7a2k1x1o7y5@neutrino.slack.com']

	[jobsuccessrate.seaquest]
		no_production = true
		voname = '/fermilab/seaquest/Role=*'
		to_emails = ['liuk.pku@gmail.com', 'bjrams@umich.edu']

	[jobsuccessrate.uboone]
		voname = '/fermilab/uboone/Role=Production/Capability=NULL'
		to_emails = ['kirby@fnal.gov', 'greenlee@fnal.gov', 'kterao@fnal.gov', 'jiangl@fnal.gov', 'joelam@fnal.gov', 'fife-group@fnal.gov']


[topwastedhoursvo]
  index_pattern='gracc.osg.summary'

 [topwastedhoursvo.darkside]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['kherner@fnal.gov',]

  [topwastedhoursvo.dune]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['trj@fnal.gov', 'tjyang@fnal.gov', 'opos@fnal.gov', 'dune-production@fnal.gov', 'schellma@fnal.gov']
    
  [topwastedhoursvo.gm2]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['tlevshin@fnal.gov', 'sbhat@fnal.gov', 'gm2-production@listserv.fnal.gov']

  [topwastedhoursvo.mu2e]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['gandr@fnal.gov', 'rlc@fnal.gov', 'kutschke@fnal.gov',  'opos@fnal.gov']

  [topwastedhoursvo.nova]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['dingpf@fnal.gov', 'opos@fnal.gov', 'o9h8i7a2k1x1o7y5@neutrino.slack.com']

  [topwastedhoursvo.seaquest]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['liuk.pku@gmail.com', 'bjrams@umich.edu']

  [topwastedhoursvo.uboone]
		perc_cutoff = 0.5
		hours_cutoff = 500
		to_emails = ['kirby@fnal.gov', 'greenlee@fnal.gov', 'kterao@fnal.gov', 'jiangl@fnal.gov', 'joelam@fnal.gov']
