# OSG base image for gracc-reporting
# FROM shreyb/gracc-reporting:base_0.7-1
FROM shreyb/gracc-reporting:osg_0.11.4b

# Executable
# ENTRYPOINT ["sh", "-c", "osgmissingprojects -s \"$starttime\" -e \"$endtime\" -r \"$reporttype\" -d"]
ENTRYPOINT ["osgmissingprojects"]
