version: "3"
services:
        osgpersitereport:
                image: "shreyb/gracc-reporting:osgpersite-report_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/gracc-config
                        - /etc/localtime:/etc/localtime
                # command: ["-s", "${starttime}", "-e", "${endtime}", "-c", "/home/gracc/gracc-config/osg.toml", "-L", "/home/gracc/log/osgflockingreport.log"]
                command: ["-s", "${starttime}", "-c", "/tmp/gracc-config/osg.toml", "-L", "/tmp/log/osgpersitereport.log", "-d"]
# osgpersitereport -s "$starttime"

